// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: artists.sql

package sqlc

import (
	"context"
)

const addArtistRelease = `-- name: AddArtistRelease :exec


INSERT INTO release_artists
(release_id, artist_id)
VALUES (?, ?)
`

type AddArtistReleaseParams struct {
	ReleaseID int64 `json:"release_id"`
	ArtistID  int64 `json:"artist_id"`
}

// -----------------------------------------------------------------------
func (q *Queries) AddArtistRelease(ctx context.Context, arg AddArtistReleaseParams) error {
	_, err := q.db.ExecContext(ctx, addArtistRelease, arg.ReleaseID, arg.ArtistID)
	return err
}

const addArtistTrack = `-- name: AddArtistTrack :exec


INSERT INTO track_artists
(track_id, artist_id, role)
VALUES (?, ?, ?)
`

type AddArtistTrackParams struct {
	TrackID  int64  `json:"track_id"`
	ArtistID int64  `json:"artist_id"`
	Role     string `json:"role"`
}

// -----------------------------------------------------------------------
func (q *Queries) AddArtistTrack(ctx context.Context, arg AddArtistTrackParams) error {
	_, err := q.db.ExecContext(ctx, addArtistTrack, arg.TrackID, arg.ArtistID, arg.Role)
	return err
}

const createArtist = `-- name: CreateArtist :one
INSERT INTO artists (name)
VALUES (?) ON CONFLICT(name) DO UPDATE SET name = name
RETURNING id, name
`

func (q *Queries) CreateArtist(ctx context.Context, name string) (Artist, error) {
	row := q.db.QueryRowContext(ctx, createArtist, name)
	var i Artist
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const deleteArtist = `-- name: DeleteArtist :exec
DELETE FROM artists
WHERE id = ?
`

func (q *Queries) DeleteArtist(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteArtist, id)
	return err
}

const getArtistById = `-- name: GetArtistById :one
SELECT id, name FROM artists
WHERE id = ?
`

func (q *Queries) GetArtistById(ctx context.Context, id int64) (Artist, error) {
	row := q.db.QueryRowContext(ctx, getArtistById, id)
	var i Artist
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const getArtistByName = `-- name: GetArtistByName :one
SELECT id, name FROM artists
WHERE name = ?
`

func (q *Queries) GetArtistByName(ctx context.Context, name string) (Artist, error) {
	row := q.db.QueryRowContext(ctx, getArtistByName, name)
	var i Artist
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const getReleaseArtists = `-- name: GetReleaseArtists :many
SELECT ar.id, ar.name
FROM release_artists ra
JOIN artists ar ON ra.artist_id = ar.id
WHERE ra.release_id = ?
ORDER BY ar.name
`

func (q *Queries) GetReleaseArtists(ctx context.Context, releaseID int64) ([]Artist, error) {
	rows, err := q.db.QueryContext(ctx, getReleaseArtists, releaseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Artist
	for rows.Next() {
		var i Artist
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTrackArtists = `-- name: GetTrackArtists :many
SELECT ar.id, ar.name, ta.role
FROM track_artists ta
JOIN artists AS ar ON ta.artist_id = ar.id
WHERE ta.track_id = ?
ORDER BY
    CASE ta.role
        WHEN 'primary' THEN 1
        WHEN 'featured' THEN 2
    END, ar.name
`

type GetTrackArtistsRow struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
	Role string `json:"role"`
}

func (q *Queries) GetTrackArtists(ctx context.Context, trackID int64) ([]GetTrackArtistsRow, error) {
	rows, err := q.db.QueryContext(ctx, getTrackArtists, trackID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTrackArtistsRow
	for rows.Next() {
		var i GetTrackArtistsRow
		if err := rows.Scan(&i.ID, &i.Name, &i.Role); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTracksByArtist = `-- name: GetTracksByArtist :many
SELECT t.id, t.title, r.name AS release_name, ta.role
FROM track_artists ta
JOIN tracks t ON ta.track_id = t.id
JOIN releases r ON t.release_id = r.id
WHERE ta.artist_id = ?
ORDER BY r.date DESC, t.track
`

type GetTracksByArtistRow struct {
	ID          int64  `json:"id"`
	Title       string `json:"title"`
	ReleaseName string `json:"release_name"`
	Role        string `json:"role"`
}

func (q *Queries) GetTracksByArtist(ctx context.Context, artistID int64) ([]GetTracksByArtistRow, error) {
	rows, err := q.db.QueryContext(ctx, getTracksByArtist, artistID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTracksByArtistRow
	for rows.Next() {
		var i GetTracksByArtistRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.ReleaseName,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listArtists = `-- name: ListArtists :many
SELECT id, name
FROM artists
ORDER BY name
`

func (q *Queries) ListArtists(ctx context.Context) ([]Artist, error) {
	rows, err := q.db.QueryContext(ctx, listArtists)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Artist
	for rows.Next() {
		var i Artist
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeReleaseArtist = `-- name: RemoveReleaseArtist :exec
DELETE FROM release_artists
WHERE release_id = ? AND artist_id = ?
`

type RemoveReleaseArtistParams struct {
	ReleaseID int64 `json:"release_id"`
	ArtistID  int64 `json:"artist_id"`
}

func (q *Queries) RemoveReleaseArtist(ctx context.Context, arg RemoveReleaseArtistParams) error {
	_, err := q.db.ExecContext(ctx, removeReleaseArtist, arg.ReleaseID, arg.ArtistID)
	return err
}

const removeTrackArtist = `-- name: RemoveTrackArtist :exec
DELETE FROM track_artists
WHERE track_id = ? AND artist_id = ?
`

type RemoveTrackArtistParams struct {
	TrackID  int64 `json:"track_id"`
	ArtistID int64 `json:"artist_id"`
}

func (q *Queries) RemoveTrackArtist(ctx context.Context, arg RemoveTrackArtistParams) error {
	_, err := q.db.ExecContext(ctx, removeTrackArtist, arg.TrackID, arg.ArtistID)
	return err
}

const updateArtist = `-- name: UpdateArtist :exec
UPDATE artists
SET name = ?
WHERE id = ?
`

type UpdateArtistParams struct {
	Name string `json:"name"`
	ID   int64  `json:"id"`
}

func (q *Queries) UpdateArtist(ctx context.Context, arg UpdateArtistParams) error {
	_, err := q.db.ExecContext(ctx, updateArtist, arg.Name, arg.ID)
	return err
}

const updateTrackArtistRole = `-- name: UpdateTrackArtistRole :exec
UPDATE track_artists
SET role = ?
WHERE track_id = ? AND artist_id = ?
`

type UpdateTrackArtistRoleParams struct {
	Role     string `json:"role"`
	TrackID  int64  `json:"track_id"`
	ArtistID int64  `json:"artist_id"`
}

func (q *Queries) UpdateTrackArtistRole(ctx context.Context, arg UpdateTrackArtistRoleParams) error {
	_, err := q.db.ExecContext(ctx, updateTrackArtistRole, arg.Role, arg.TrackID, arg.ArtistID)
	return err
}
