// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audio_files.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createAudioFile = `-- name: CreateAudioFile :one
INSERT INTO audio_files
(name, codec, bit_rate, bit_depth, channels, sample_rate, size)
VALUES (?, ?, ?, ?, ?, ?, ?)
RETURNING id, name, codec, bit_rate, bit_depth, channels, sample_rate, size
`

type CreateAudioFileParams struct {
	Name       string        `json:"name"`
	Codec      string        `json:"codec"`
	BitRate    sql.NullInt64 `json:"bit_rate"`
	BitDepth   sql.NullInt64 `json:"bit_depth"`
	Channels   sql.NullInt64 `json:"channels"`
	SampleRate int64         `json:"sample_rate"`
	Size       int64         `json:"size"`
}

func (q *Queries) CreateAudioFile(ctx context.Context, arg CreateAudioFileParams) (AudioFile, error) {
	row := q.db.QueryRowContext(ctx, createAudioFile,
		arg.Name,
		arg.Codec,
		arg.BitRate,
		arg.BitDepth,
		arg.Channels,
		arg.SampleRate,
		arg.Size,
	)
	var i AudioFile
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Codec,
		&i.BitRate,
		&i.BitDepth,
		&i.Channels,
		&i.SampleRate,
		&i.Size,
	)
	return i, err
}

const deleteAudioFile = `-- name: DeleteAudioFile :exec
DELETE FROM audio_files
WHERE id = ?
`

func (q *Queries) DeleteAudioFile(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteAudioFile, id)
	return err
}

const getAudioFileById = `-- name: GetAudioFileById :one
SELECT id, name, codec, bit_rate, bit_depth, channels, sample_rate, size FROM audio_files
WHERE id = ?
`

func (q *Queries) GetAudioFileById(ctx context.Context, id int64) (AudioFile, error) {
	row := q.db.QueryRowContext(ctx, getAudioFileById, id)
	var i AudioFile
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Codec,
		&i.BitRate,
		&i.BitDepth,
		&i.Channels,
		&i.SampleRate,
		&i.Size,
	)
	return i, err
}
