// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: covers.sql

package sqlc

import (
	"context"
)

const createCover = `-- name: CreateCover :one
INSERT INTO covers (name, thumb_name) VALUES (?, ?)
RETURNING id, name, thumb_name
`

type CreateCoverParams struct {
	Name      string `json:"name"`
	ThumbName string `json:"thumb_name"`
}

func (q *Queries) CreateCover(ctx context.Context, arg CreateCoverParams) (Cover, error) {
	row := q.db.QueryRowContext(ctx, createCover, arg.Name, arg.ThumbName)
	var i Cover
	err := row.Scan(&i.ID, &i.Name, &i.ThumbName)
	return i, err
}

const deleteCover = `-- name: DeleteCover :exec
DELETE FROM covers WHERE id = ?
`

func (q *Queries) DeleteCover(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteCover, id)
	return err
}

const getCoverById = `-- name: GetCoverById :one
SELECT id, name, thumb_name FROM covers
WHERE id = ?
`

func (q *Queries) GetCoverById(ctx context.Context, id int64) (Cover, error) {
	row := q.db.QueryRowContext(ctx, getCoverById, id)
	var i Cover
	err := row.Scan(&i.ID, &i.Name, &i.ThumbName)
	return i, err
}

const listCovers = `-- name: ListCovers :many
SELECT id, name, thumb_name FROM covers
LIMIT ? OFFSET ?
`

type ListCoversParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) ListCovers(ctx context.Context, arg ListCoversParams) ([]Cover, error) {
	rows, err := q.db.QueryContext(ctx, listCovers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Cover
	for rows.Next() {
		var i Cover
		if err := rows.Scan(&i.ID, &i.Name, &i.ThumbName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
