// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"database/sql"
)

type Artist struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
}

type AudioFile struct {
	ID         int64         `json:"id"`
	Name       string        `json:"name"`
	Codec      string        `json:"codec"`
	BitRate    sql.NullInt64 `json:"bit_rate"`
	BitDepth   sql.NullInt64 `json:"bit_depth"`
	Channels   sql.NullInt64 `json:"channels"`
	SampleRate int64         `json:"sample_rate"`
	Size       int64         `json:"size"`
}

type Cover struct {
	ID        int64  `json:"id"`
	Name      string `json:"name"`
	ThumbName string `json:"thumb_name"`
}

type Release struct {
	ID          int64          `json:"id"`
	Title       string         `json:"title"`
	Name        string         `json:"name"`
	ReleaseType string         `json:"release_type"`
	Date        sql.NullString `json:"date"`
	TotalTracks int64          `json:"total_tracks"`
	TotalDiscs  int64          `json:"total_discs"`
	CoverID     sql.NullInt64  `json:"cover_id"`
}

type ReleaseArtist struct {
	ReleaseID int64 `json:"release_id"`
	ArtistID  int64 `json:"artist_id"`
}

type Track struct {
	ID          int64          `json:"id"`
	Title       string         `json:"title"`
	Duration    float64        `json:"duration"`
	Track       int64          `json:"track"`
	Disc        int64          `json:"disc"`
	Composer    sql.NullString `json:"composer"`
	Lyrics      sql.NullString `json:"lyrics"`
	ReleaseID   int64          `json:"release_id"`
	AudioFileID int64          `json:"audio_file_id"`
}

type TrackArtist struct {
	TrackID  int64  `json:"track_id"`
	ArtistID int64  `json:"artist_id"`
	Role     string `json:"role"`
}
