// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"
	"database/sql"
)

type Querier interface {
	//-----------------------------------------------------------------------
	AddArtistRelease(ctx context.Context, arg AddArtistReleaseParams) error
	//-----------------------------------------------------------------------
	AddArtistTrack(ctx context.Context, arg AddArtistTrackParams) error
	CreateArtist(ctx context.Context, name string) (Artist, error)
	CreateAudioFile(ctx context.Context, arg CreateAudioFileParams) (AudioFile, error)
	CreateCover(ctx context.Context, arg CreateCoverParams) (Cover, error)
	CreateRelease(ctx context.Context, arg CreateReleaseParams) (Release, error)
	CreateTrack(ctx context.Context, arg CreateTrackParams) (Track, error)
	DeleteArtist(ctx context.Context, id int64) error
	DeleteAudioFile(ctx context.Context, id int64) error
	DeleteCover(ctx context.Context, id int64) error
	DeleteRelease(ctx context.Context, id int64) error
	DeleteTrack(ctx context.Context, id int64) error
	GetArtistById(ctx context.Context, id int64) (Artist, error)
	GetArtistByName(ctx context.Context, name string) (Artist, error)
	GetAudioFileById(ctx context.Context, id int64) (AudioFile, error)
	GetCoverById(ctx context.Context, id int64) (Cover, error)
	GetReleaseArtists(ctx context.Context, releaseID int64) ([]Artist, error)
	GetReleaseById(ctx context.Context, id int64) (Release, error)
	GetReleaseCover(ctx context.Context, id int64) (GetReleaseCoverRow, error)
	GetReleaseDuration(ctx context.Context, releaseID int64) (sql.NullFloat64, error)
	GetTrackArtists(ctx context.Context, trackID int64) ([]GetTrackArtistsRow, error)
	GetTrackById(ctx context.Context, id int64) (GetTrackByIdRow, error)
	GetTracksByArtist(ctx context.Context, artistID int64) ([]GetTracksByArtistRow, error)
	ListArtists(ctx context.Context) ([]Artist, error)
	ListCovers(ctx context.Context, arg ListCoversParams) ([]Cover, error)
	ListReleases(ctx context.Context, arg ListReleasesParams) ([]ListReleasesRow, error)
	ListTracksRelease(ctx context.Context, releaseID int64) ([]ListTracksReleaseRow, error)
	RemoveReleaseArtist(ctx context.Context, arg RemoveReleaseArtistParams) error
	RemoveTrackArtist(ctx context.Context, arg RemoveTrackArtistParams) error
	UpdateArtist(ctx context.Context, arg UpdateArtistParams) error
	UpdateRelease(ctx context.Context, arg UpdateReleaseParams) (Release, error)
	UpdateReleaseCover(ctx context.Context, arg UpdateReleaseCoverParams) error
	UpdateTrack(ctx context.Context, arg UpdateTrackParams) (Track, error)
	UpdateTrackArtistRole(ctx context.Context, arg UpdateTrackArtistRoleParams) error
}

var _ Querier = (*Queries)(nil)
