// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: releases.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createRelease = `-- name: CreateRelease :one
INSERT INTO releases
(title, name, release_type, date, total_tracks, total_discs, cover_id)
VALUES (?, ?, ?, ?, ?, ?, ?)
RETURNING id, title, name, release_type, date, total_tracks, total_discs, cover_id
`

type CreateReleaseParams struct {
	Title       string         `json:"title"`
	Name        string         `json:"name"`
	ReleaseType string         `json:"release_type"`
	Date        sql.NullString `json:"date"`
	TotalTracks int64          `json:"total_tracks"`
	TotalDiscs  int64          `json:"total_discs"`
	CoverID     sql.NullInt64  `json:"cover_id"`
}

func (q *Queries) CreateRelease(ctx context.Context, arg CreateReleaseParams) (Release, error) {
	row := q.db.QueryRowContext(ctx, createRelease,
		arg.Title,
		arg.Name,
		arg.ReleaseType,
		arg.Date,
		arg.TotalTracks,
		arg.TotalDiscs,
		arg.CoverID,
	)
	var i Release
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Name,
		&i.ReleaseType,
		&i.Date,
		&i.TotalTracks,
		&i.TotalDiscs,
		&i.CoverID,
	)
	return i, err
}

const deleteRelease = `-- name: DeleteRelease :exec
DELETE FROM releases
WHERE id = ?
`

func (q *Queries) DeleteRelease(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteRelease, id)
	return err
}

const getReleaseById = `-- name: GetReleaseById :one
SELECT id, title, name, release_type, date, total_tracks, total_discs, cover_id FROM releases
WHERE id = ?
`

func (q *Queries) GetReleaseById(ctx context.Context, id int64) (Release, error) {
	row := q.db.QueryRowContext(ctx, getReleaseById, id)
	var i Release
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Name,
		&i.ReleaseType,
		&i.Date,
		&i.TotalTracks,
		&i.TotalDiscs,
		&i.CoverID,
	)
	return i, err
}

const getReleaseCover = `-- name: GetReleaseCover :one
SELECT r.id, r.name, c.id, c.name, c.thumb_name FROM releases AS r
JOIN covers AS c ON  r.cover_id = c.id
WHERE r.id = ?
`

type GetReleaseCoverRow struct {
	ID        int64  `json:"id"`
	Name      string `json:"name"`
	ID_2      int64  `json:"id_2"`
	Name_2    string `json:"name_2"`
	ThumbName string `json:"thumb_name"`
}

func (q *Queries) GetReleaseCover(ctx context.Context, id int64) (GetReleaseCoverRow, error) {
	row := q.db.QueryRowContext(ctx, getReleaseCover, id)
	var i GetReleaseCoverRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ID_2,
		&i.Name_2,
		&i.ThumbName,
	)
	return i, err
}

const getReleaseDuration = `-- name: GetReleaseDuration :one
SELECT SUM(duration) AS total_duration
FROM tracks
WHERE release_id = ?
`

func (q *Queries) GetReleaseDuration(ctx context.Context, releaseID int64) (sql.NullFloat64, error) {
	row := q.db.QueryRowContext(ctx, getReleaseDuration, releaseID)
	var total_duration sql.NullFloat64
	err := row.Scan(&total_duration)
	return total_duration, err
}

const listReleases = `-- name: ListReleases :many
SELECT id, title, release_type, date, total_tracks, total_discs, cover_id
FROM releases
LIMIT ? OFFSET ?
`

type ListReleasesParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

type ListReleasesRow struct {
	ID          int64          `json:"id"`
	Title       string         `json:"title"`
	ReleaseType string         `json:"release_type"`
	Date        sql.NullString `json:"date"`
	TotalTracks int64          `json:"total_tracks"`
	TotalDiscs  int64          `json:"total_discs"`
	CoverID     sql.NullInt64  `json:"cover_id"`
}

func (q *Queries) ListReleases(ctx context.Context, arg ListReleasesParams) ([]ListReleasesRow, error) {
	rows, err := q.db.QueryContext(ctx, listReleases, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListReleasesRow
	for rows.Next() {
		var i ListReleasesRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.ReleaseType,
			&i.Date,
			&i.TotalTracks,
			&i.TotalDiscs,
			&i.CoverID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTracksRelease = `-- name: ListTracksRelease :many
SELECT t.id, t.title, t.duration, t.track, t.disc, t.composer, t.audio_file_id
FROM tracks AS t
WHERE t.release_id = ?
`

type ListTracksReleaseRow struct {
	ID          int64          `json:"id"`
	Title       string         `json:"title"`
	Duration    float64        `json:"duration"`
	Track       int64          `json:"track"`
	Disc        int64          `json:"disc"`
	Composer    sql.NullString `json:"composer"`
	AudioFileID int64          `json:"audio_file_id"`
}

func (q *Queries) ListTracksRelease(ctx context.Context, releaseID int64) ([]ListTracksReleaseRow, error) {
	rows, err := q.db.QueryContext(ctx, listTracksRelease, releaseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTracksReleaseRow
	for rows.Next() {
		var i ListTracksReleaseRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Duration,
			&i.Track,
			&i.Disc,
			&i.Composer,
			&i.AudioFileID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRelease = `-- name: UpdateRelease :one
UPDATE releases
SET title = ?, release_type = ?, date = ?, total_tracks = ?, total_discs = ?
WHERE id = ?
RETURNING id, title, name, release_type, date, total_tracks, total_discs, cover_id
`

type UpdateReleaseParams struct {
	Title       string         `json:"title"`
	ReleaseType string         `json:"release_type"`
	Date        sql.NullString `json:"date"`
	TotalTracks int64          `json:"total_tracks"`
	TotalDiscs  int64          `json:"total_discs"`
	ID          int64          `json:"id"`
}

func (q *Queries) UpdateRelease(ctx context.Context, arg UpdateReleaseParams) (Release, error) {
	row := q.db.QueryRowContext(ctx, updateRelease,
		arg.Title,
		arg.ReleaseType,
		arg.Date,
		arg.TotalTracks,
		arg.TotalDiscs,
		arg.ID,
	)
	var i Release
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Name,
		&i.ReleaseType,
		&i.Date,
		&i.TotalTracks,
		&i.TotalDiscs,
		&i.CoverID,
	)
	return i, err
}

const updateReleaseCover = `-- name: UpdateReleaseCover :exec
UPDATE releases
SET cover_id = ?
WHERE id = ?
`

type UpdateReleaseCoverParams struct {
	CoverID sql.NullInt64 `json:"cover_id"`
	ID      int64         `json:"id"`
}

func (q *Queries) UpdateReleaseCover(ctx context.Context, arg UpdateReleaseCoverParams) error {
	_, err := q.db.ExecContext(ctx, updateReleaseCover, arg.CoverID, arg.ID)
	return err
}
