// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tracks.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createTrack = `-- name: CreateTrack :one
INSERT INTO tracks
(title, duration, track, disc, composer, lyrics, release_id, audio_file_id)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, title, duration, track, disc, composer, lyrics, release_id, audio_file_id
`

type CreateTrackParams struct {
	Title       string         `json:"title"`
	Duration    float64        `json:"duration"`
	Track       int64          `json:"track"`
	Disc        int64          `json:"disc"`
	Composer    sql.NullString `json:"composer"`
	Lyrics      sql.NullString `json:"lyrics"`
	ReleaseID   int64          `json:"release_id"`
	AudioFileID int64          `json:"audio_file_id"`
}

func (q *Queries) CreateTrack(ctx context.Context, arg CreateTrackParams) (Track, error) {
	row := q.db.QueryRowContext(ctx, createTrack,
		arg.Title,
		arg.Duration,
		arg.Track,
		arg.Disc,
		arg.Composer,
		arg.Lyrics,
		arg.ReleaseID,
		arg.AudioFileID,
	)
	var i Track
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Duration,
		&i.Track,
		&i.Disc,
		&i.Composer,
		&i.Lyrics,
		&i.ReleaseID,
		&i.AudioFileID,
	)
	return i, err
}

const deleteTrack = `-- name: DeleteTrack :exec
DELETE FROM tracks
WHERE id = ?
`

func (q *Queries) DeleteTrack(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteTrack, id)
	return err
}

const getTrackById = `-- name: GetTrackById :one
SELECT t.id, t.title, t.duration, t.track, t.disc, t.composer, t.lyrics,
       r.id AS release_id, r.title AS release_title, r.name AS release_name,
       af.id AS audio_file_id, af.name AS audio_file_name, af.codec, af.bit_rate, af.bit_depth,
       af.channels, af.sample_rate, af.size
FROM tracks AS t
JOIN releases AS r ON t.release_id = r.id
JOIN audio_files AS af ON t.audio_file_id = af.id
WHERE t.id = ?
`

type GetTrackByIdRow struct {
	ID            int64          `json:"id"`
	Title         string         `json:"title"`
	Duration      float64        `json:"duration"`
	Track         int64          `json:"track"`
	Disc          int64          `json:"disc"`
	Composer      sql.NullString `json:"composer"`
	Lyrics        sql.NullString `json:"lyrics"`
	ReleaseID     int64          `json:"release_id"`
	ReleaseTitle  string         `json:"release_title"`
	ReleaseName   string         `json:"release_name"`
	AudioFileID   int64          `json:"audio_file_id"`
	AudioFileName string         `json:"audio_file_name"`
	Codec         string         `json:"codec"`
	BitRate       sql.NullInt64  `json:"bit_rate"`
	BitDepth      sql.NullInt64  `json:"bit_depth"`
	Channels      sql.NullInt64  `json:"channels"`
	SampleRate    int64          `json:"sample_rate"`
	Size          int64          `json:"size"`
}

func (q *Queries) GetTrackById(ctx context.Context, id int64) (GetTrackByIdRow, error) {
	row := q.db.QueryRowContext(ctx, getTrackById, id)
	var i GetTrackByIdRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Duration,
		&i.Track,
		&i.Disc,
		&i.Composer,
		&i.Lyrics,
		&i.ReleaseID,
		&i.ReleaseTitle,
		&i.ReleaseName,
		&i.AudioFileID,
		&i.AudioFileName,
		&i.Codec,
		&i.BitRate,
		&i.BitDepth,
		&i.Channels,
		&i.SampleRate,
		&i.Size,
	)
	return i, err
}

const updateTrack = `-- name: UpdateTrack :one
UPDATE tracks
SET title = ?, duration = ?, track = ?, disc = ?, composer = ?, lyrics = ?
WHERE id = ?
RETURNING id, title, duration, track, disc, composer, lyrics, release_id, audio_file_id
`

type UpdateTrackParams struct {
	Title    string         `json:"title"`
	Duration float64        `json:"duration"`
	Track    int64          `json:"track"`
	Disc     int64          `json:"disc"`
	Composer sql.NullString `json:"composer"`
	Lyrics   sql.NullString `json:"lyrics"`
	ID       int64          `json:"id"`
}

func (q *Queries) UpdateTrack(ctx context.Context, arg UpdateTrackParams) (Track, error) {
	row := q.db.QueryRowContext(ctx, updateTrack,
		arg.Title,
		arg.Duration,
		arg.Track,
		arg.Disc,
		arg.Composer,
		arg.Lyrics,
		arg.ID,
	)
	var i Track
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Duration,
		&i.Track,
		&i.Disc,
		&i.Composer,
		&i.Lyrics,
		&i.ReleaseID,
		&i.AudioFileID,
	)
	return i, err
}
